<a href="https://colab.research.google.com/github/Willi-blip/numpy/blob/main/Ejercicios_basicos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPY, Libreria de ciencia de datos

In [2]:
import numpy as np
#pip install numpy

ARRAYS DE 1 DIMENSION

In [3]:
array_id=np.array([10,20,30])
print(array_id)

[10 20 30]


In [4]:
array_id

array([10, 20, 30])

ARRAYS DE 2 DIMENSIONES

In [5]:
array_2d=np.array([(10,20,30),(40,50,50)])
array_2d

array([[10, 20, 30],
       [40, 50, 50]])

ARRATS DE 3 DIMENSIONES

In [21]:
array_3d=np.array([(10,20,30),(40,50,60),(70,80,90)],dtype=float)
array_3d

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

ARRAY CON 0 DE 3 FILAS 4 CULUMNAS

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


ARRAY DE UNOS CON2 DIMENSIONES 4 FILAS 5 COLUMNAS

In [18]:
np.ones([2,4,5])

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

ARRAYS INTERVALOS Y SALTOS

In [16]:
np.arange(11,30,2)

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

ARRAYS CON INTERVALOS Y DIVISIONES

In [17]:
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

ARRAY CON VALORES DADOS

In [15]:
np.full([3,3],7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

ARRAY MATRIZ IDENTIDAD, DIAGONAL, DE UNOS

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

ARRAY VALORES ALEATORIOS

In [13]:
np.random.random((4,4))

array([[0.60514993, 0.53066381, 0.3716438 , 0.30570914],
       [0.77986464, 0.74715728, 0.95160871, 0.94113305],
       [0.21380297, 0.94062382, 0.37928784, 0.51552775],
       [0.5057371 , 0.59553668, 0.68879215, 0.77782114]])

ARRAY NUMEROS VACIOS 4*3

In [12]:
np.empty((4,3))

array([[6.87486520e-310, 0.00000000e+000, 2.10077583e-312],
       [6.79038654e-313, 2.22809558e-312, 2.14321575e-312],
       [2.35541533e-312, 6.79038654e-313, 2.22809558e-312],
       [2.14321575e-312, 2.46151512e-312, 2.41907520e-312]])

GRABAR Y CARGAR

In [23]:
#grabar
np.save('mi_array_3d',array_3d)

In [24]:
#cargar
mi_array=np.load('mi_array_3d.npy')
mi_array

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

In [ ]:
np.save('mi_array_2d',array_2d)

In [ ]:
mi_array=np.load('mi_array_2d.npy')
mi_array

array([[10, 20, 30],
       [40, 50, 50]])

GRABAR Y CARGAR FICHEROS DE TEXTOS

In [ ]:
#grabar el fichero de texto
np.savetxt('mi_array.txt',array_2d,delimiter=' ')

In [ ]:
#cargar el fichero de texto
np.loadtxt('mi_array.txt')

array([[10., 20., 30.],
       [40., 50., 50.]])

EJECICIOS PROPUETO

In [ ]:
asignaturas = ["Matemáticas", "Física", "Química", "Historia", "Lengua"]
asignaturas

['Matemáticas', 'Física', 'Química', 'Historia', 'Lengua']

In [ ]:
for asignatura in asignaturas:
    print("Yo estudio " + asignatura)

Yo estudio Matemáticas
Yo estudio Física
Yo estudio Química
Yo estudio Historia
Yo estudio Lengua


In [ ]:
notas = []
for asignatura in asignaturas:
  nota = input("¿Qué nota has sacado en {}? ".format(asignatura))
  notas.append(nota)

for i in range(len(asignaturas)):
  print("En {} has sacado: {}".format(asignaturas[i], notas[i]))

¿Qué nota has sacado en Matemáticas? 15
¿Qué nota has sacado en Física? 15
¿Qué nota has sacado en Química? 14
¿Qué nota has sacado en Historia? 13
¿Qué nota has sacado en Lengua? 16
En Matemáticas has sacado: 15
En Física has sacado: 15
En Química has sacado: 14
En Historia has sacado: 13
En Lengua has sacado: 16


In [ ]:
numeros_ganadores = []
while len(numeros_ganadores) < 6:
  try:
    numero = int(input(f"Introduce el número {len(numeros_ganadores) + 1} de la lotería: "))
    if 1 <= numero <= 50 and numero not in numeros_ganadores:
      numeros_ganadores.append(numero)
    elif numero in numeros_ganadores:
      print("Ese número ya ha sido introducido. Introduce uno diferente.")
    else:
      print("El número debe estar entre 1 y 50.")
  except ValueError:
    print("Entrada no válida. Por favor, introduce un número entero.")

numeros_ganadores.sort()
print("Los números ganadores de la lotería primitiva son:")
numeros_ganadores


Introduce el número 1 de la lotería: 1
Introduce el número 2 de la lotería: 5
Introduce el número 3 de la lotería: 49
Introduce el número 4 de la lotería: 7
Introduce el número 5 de la lotería: 23
Introduce el número 6 de la lotería: 24
Los números ganadores de la lotería primitiva son:


[1, 5, 7, 23, 24, 49]

In [ ]:
numeros = list(range(1, 11))
numeros.reverse()
print(",".join(map(str, numeros)))

1,2,3,4,5,6,7,8,9,10


In [ ]:
asignaturas = ["Matemáticas", "Física", "Química", "Historia", "Lengua"]
notas = []
for asignatura in asignaturas:
    while True:
        try:
            nota = float(input(f"¿Qué nota has sacado en {asignatura}? "))
            if 0 <= nota <= 20:
                notas.append(nota)
                break
            else:
                print("Por favor, introduce una nota entre 0 y 10.")
        except ValueError:
            print("Entrada no válida. Por favor, introduce un número para la nota.")

asignaturas_a_repetir = []
for i in range(len(asignaturas)):
    if notas[i] < 10:
        asignaturas_a_repetir.append(asignaturas[i])

if asignaturas_a_repetir:
    print("\nAsignaturas que tienes que repetir:")
    for asignatura in asignaturas_a_repetir:
        print(asignatura)
else:
    print("\n¡Enhorabuena! Has aprobado todas las asignaturas.")

¿Qué nota has sacado en Matemáticas? 9
¿Qué nota has sacado en Física? 15
¿Qué nota has sacado en Química? 15
¿Qué nota has sacado en Historia? 20
¿Qué nota has sacado en Lengua? 8

Asignaturas que tienes que repetir:
Matemáticas
Lengua


In [ ]:
alfabeto = list('abcdefghijklmnopqrstuvwxyz')
alfabeto_filtrado = [letra for indice, letra in enumerate(alfabeto) if (indice + 1) % 3 != 0]
alfabeto_filtrado

['a',
 'b',
 'd',
 'e',
 'g',
 'h',
 'j',
 'k',
 'm',
 'n',
 'p',
 'q',
 's',
 't',
 'v',
 'w',
 'y',
 'z']

In [ ]:
palabra = input("Introduce una palabra: ")
palabra = palabra.lower().replace(" ", "")
if palabra == palabra[::-1]:
  print("Es un palíndromo.")
else:
  print("No es un palíndromo.")

Introduce una palabra: we
No es un palíndromo.


In [ ]:
palabra = input("Introduce una palabra: ").lower()
vocales = {'a': 0, 'e': 0, 'i': 0, 'o': 0, 'u': 0}
for letra in palabra:
  if letra in vocales:
    vocales[letra] += 1
for vocal, count in vocales.items():
  print(f"La vocal '{vocal}' aparece {count} veces.")

Introduce una palabra: palabra
La vocal 'a' aparece 3 veces.
La vocal 'e' aparece 0 veces.
La vocal 'i' aparece 0 veces.
La vocal 'o' aparece 0 veces.
La vocal 'u' aparece 0 veces.


In [25]:
precios = [50, 75, 46, 22, 80, 65, 8]
print("El precio menor es:", min(precios))
print("El precio mayor es:", max(precios))

El precio menor es: 8
El precio mayor es: 80


In [26]:
# Vectores en listas
vector1 = [1, 2, 3]
vector2 = [-1, 0, 2]

# Calcular el producto escalar
producto_escalar = sum(x * y for x, y in zip(vector1, vector2))

# Mostrar el resultado
print(f"El producto escalar de {vector1} y {vector2} es: {producto_escalar}")

El producto escalar de [1, 2, 3] y [-1, 0, 2] es: 5


In [27]:
# Definir las matrices como listas anidadas
matriz1 = [[1, 2],
           [3, 4]]

matriz2 = [[5, 6],
           [7, 8]]

# Almacenar las matrices en una lista
matrices = [matriz1, matriz2]

# Función para multiplicar dos matrices
def multiplicar_matrices(matriz_a, matriz_b):
    # Verificar si la multiplicación es posible
    if len(matriz_a[0]) != len(matriz_b):
        return "No se pueden multiplicar las matrices."

    # Inicializar la matriz resultado con ceros
    filas_a = len(matriz_a)
    columnas_a = len(matriz_a[0])
    filas_b = len(matriz_b)
    columnas_b = len(matriz_b[0])
    matriz_resultado = [[0 for _ in range(columnas_b)] for _ in range(filas_a)]

    # Realizar la multiplicación
    for i in range(filas_a):
        for j in range(columnas_b):
            for k in range(columnas_a):
                matriz_resultado[i][j] += matriz_a[i][k] * matriz_b[k][j]

    return matriz_resultado

# Calcular el producto de las matrices en la lista
if len(matrices) >= 2:
    producto = matrices[0]
    for i in range(1, len(matrices)):
        producto = multiplicar_matrices(producto, matrices[i])
        if isinstance(producto, str): # Verificar si hubo error en la multiplicación
            print(producto)
            break
    else:
        print("El producto de las matrices es:")
        for fila in producto:
            print(fila)
elif len(matrices) == 1:
    print("Solo hay una matriz en la lista:")
    for fila in matrices[0]:
        print(fila)
else:
    print("La lista de matrices está vacía.")

El producto de las matrices es:
[19, 22]
[43, 50]


In [29]:
import numpy as np

entrada = input("Introduce una muestra de números separados por comas: ")
numeros_str = entrada.split(',')
numeros = []
for num_str in numeros_str:
  try:
    numeros.append(float(num_str.strip()))
  except ValueError:
    print(f"Advertencia: '{num_str.strip()}' no es un número válido y será ignorado.")

if numeros:
  muestra = np.array(numeros)
  media = np.mean(muestra)
  desviacion_tipica = np.std(muestra)

  print(f"La muestra es: {numeros}")
  print(f"La media es: {media}")
  print(f"La desviación típica es: {desviacion_tipica}")
else:
  print("No se introdujeron números válidos.")


Introduce una muestra de números separados por comas: 23,5
La muestra es: [23.0, 5.0]
La media es: 14.0
La desviación típica es: 9.0
